In [3]:
%matplotlib inline
import seaborn as sns

In [28]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
x_iris=iris.drop('species', axis=1)
x_iris

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [12]:
y_iris=iris['species']
y_iris

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [14]:
from sklearn.model_selection import train_test_split

In [30]:
xtest, xtrain, ytest, ytrain = train_test_split(x_iris, y_iris, random_state=1)
xtest

     sepal_length  sepal_width  petal_length  petal_width
54            6.5          2.8           4.6          1.5
108           6.7          2.5           5.8          1.8
112           6.8          3.0           5.5          2.1
17            5.1          3.5           1.4          0.3
119           6.0          2.2           5.0          1.5
..            ...          ...           ...          ...
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
72            6.3          2.5           4.9          1.5
140           6.7          3.1           5.6          2.4
37            4.9          3.6           1.4          0.1

[112 rows x 4 columns]

In [17]:
xtest, xtrain, ytest, ytrain = train_test_split(x_iris, y_iris, random_state=1)
xtrain

     sepal_length  sepal_width  petal_length  petal_width
14            5.8          4.0           1.2          0.2
98            5.1          2.5           3.0          1.1
75            6.6          3.0           4.4          1.4
16            5.4          3.9           1.3          0.4
131           7.9          3.8           6.4          2.0
56            6.3          3.3           4.7          1.6
141           6.9          3.1           5.1          2.3
44            5.1          3.8           1.9          0.4
29            4.7          3.2           1.6          0.2
120           6.9          3.2           5.7          2.3
94            5.6          2.7           4.2          1.3
5             5.4          3.9           1.7          0.4
102           7.1          3.0           5.9          2.1
51            6.4          3.2           4.5          1.5
78            6.0          2.9           4.5          1.5
42            4.4          3.2           1.3          0.2
92            5.8          2.6           4.0          1.2
66            5.6          3.0           4.5          1.5
31            5.4          3.4           1.5          0.4
35            5.0          3.2           1.2          0.2
90            5.5          2.6           4.4          1.2
84            5.4          3.0           4.5          1.5
77            6.7          3.0           5.0          1.7
40            5.0          3.5           1.3          0.3
125           7.2          3.2           6.0          1.8
99            5.7          2.8           4.1          1.3
33            5.5          4.2           1.4          0.2
19            5.1          3.8           1.5          0.3
73            6.1          2.8           4.7          1.2
146           6.3          2.5           5.0          1.9
91            6.1          3.0           4.6          1.4
135           7.7          3.0           6.1          2.3
69            5.6          2.5           3.9          1.1
128           6.4          2.8           5.6          2.1
114           5.8          2.8           5.1          2.4
48            5.3          3.7           1.5          0.2
53            5.5          2.3           4.0          1.3
28            5.2          3.4           1.4          0.2

In [18]:
xtest, xtrain, ytest, ytrain = train_test_split(x_iris, y_iris, random_state=1)
ytrain

14         setosa
98     versicolor
75     versicolor
16         setosa
131     virginica
56     versicolor
141     virginica
44         setosa
29         setosa
120     virginica
94     versicolor
5          setosa
102     virginica
51     versicolor
78     versicolor
42         setosa
92     versicolor
66     versicolor
31         setosa
35         setosa
90     versicolor
84     versicolor
77     versicolor
40         setosa
125     virginica
99     versicolor
33         setosa
19         setosa
73     versicolor
146     virginica
91     versicolor
135     virginica
69     versicolor
128     virginica
114     virginica
48         setosa
53     versicolor
28         setosa
Name: species, dtype: object

In [19]:
xtest, xtrain, ytest, ytrain = train_test_split(x_iris, y_iris, random_state=1)
ytest

54     versicolor
108     virginica
112     virginica
17         setosa
119     virginica
          ...
133     virginica
137     virginica
72     versicolor
140     virginica
37         setosa
Name: species, Length: 112, dtype: object

In [20]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [21]:
model.fit(xtrain, ytrain)

GaussianNB()

In [23]:
y_model=model.predict(xtest)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_model)

0.9285714285714286